### PR TITLE
add stock keyboard layout of Kinesis Advantage

### PR DESCRIPTION
**Pull request by alerque**
This is the [Kinesis Advantage](http://www.kinesis-ergo.com/shop/advantage-for-pc-mac/) keyboard layout as it comes from the factory. As the keyboard includes on-board remapping functions it is a great candidate for this app. Users are going to end up with layouts that differ from what is printed on the keys and want to keep track of their layouts visually.

### CODE REVIEW

**Comment by D1SC0tech** [comment]
The author has not been active on this project for over a year, so I've created my own [fork](https://github.com/d1sc0tech/keyboard-layout-editor). It doesn't work perfectly yet, but I've made some changes and pulled in this PR.

**Comment by alerque** [comment]
No actually you didn't pull in this PR. You ripped the data off and dropped it in your fork without any credit at all.

Look I'm happy to see there is some life in this tool yet because I think it's great. However there seem to be a couple problems here and I'd like to know how your fork is addressing them.

1. The code doesn't have a proper OSS license. In fact it's marked as being all rights reserved to the original author. Have you contacted the author to address that?
2. Is your fork hosted somewhere that other people can run? If so where (the address listed in the README doesn't even resolve properly in DNS) and how are you dealing with ①? 
3. Please learn to use `git cherry-pick` man. It's not the end of the world but when people contribute to projects like this the best way to thank them is to keep their names on their commits.

**Comment by D1SC0tech** [comment]
Oh man, I am so sorry about that. I'm gonna learn to use `cherry-pick` and then I'll properly pull this in. Again, I'm so sorry.

1. @iandoug and I have tried contacting him multiple times, but he has not yet responded. I won't publish it until I get through to him.
2. Yes, I accidentally left a branded URL in the README, I've just fixed it.
3. Will do, for yours and any others.

**Comment by alerque** [comment]
Alright, sounds like a fair game plan for now. I really hope the guy shows up and we can straighten out the license issues. For now I'll rebase off of your fork. I'm not quite sure what to do with this PR as it will be obsolete, but I guess I'll close it. @ijprest if you ever do come round here please poke me/us as I'd love help resolve this properly.

**Comment by ijprest** [comment]
OK, I've merged this, and fixed the corresponding issue #81.

**Pull request closed without merging**
