### PR TITLE
Add DSA dish

### PR DESCRIPTION
**Pull request by D1SC0tech**
First off, absolutely LOVE keyboard-layout-editor. However, it looks like the project has been dormant for a while. Is there any way you would consider giving write access to someone else from the community so that they might continue to improve it?

This pull request: I was missing DSA dishes, so I decided to add them. Only tested on Firefox so far, but looks good IMHO.

### CODE REVIEW

**Comment by ijprest** [comment]
I think this has already diverged too much for me to just pull the whole thing.  Did you want me to try to cherry-pick some commits?

**Comment by D1SC0tech** [comment]
Definitely. I'm currently on vacation and have crappy internet, so I won't be able to fix things for a bit, but I think just 55e3a11 should cover it.

**Comment by ijprest** [comment]
OK, I've cherry-picked 55e3a11192b01dacb1982be7045c860f86546180, and also updated the "Retro DSA" sample to show it off.  The effect is subtle (with that color-scheme, at least), but looks pretty good.

I'll close this PR for now, but feel free to send anything else in the future... and I'll endeavour to address it more quickly than I did this one! :)

**Comment by D1SC0tech** [comment]
Fantastic, it looks great! I'll let you know if I have anything new.

**Pull request closed without merging**
