### PR TITLE
Bulk moves etc

### PR DESCRIPTION
**Pull request by iandoug**
I know you are busy, you can look at this when you have time. Your art director will likely have a heart attack. Improvements to the GUI welcome :-) 
tools-dialogue
Anyway, it's aimed at #127.
I've added a Tools dialogue with following functions:

1. Remove various classes of legends from the keys ... either 'selected' or all if nothing selected. It's a quick way to get a blank layout, or for example, you want to use standard 104 as Dvorak, you can just wipe the Alphas.

2. Move vertical pairs of legends to another column on the keys (selected or all).
3. Swap top and bottom legends in left column on key (selected or all)

4. Move legends from one slot to another (selected or all)

5. Unhide the decal keys ... in case you have trouble finding it, or if you wiped the decal in (1) above.

### CODE REVIEW

**Comment by iandoug** [comment]
Realised today that I'm moving the legend, but not the colour, font, fontsize etc ... will look at fixing that.

**Comment by ijprest** [comment]
I've started looking at this... might take me a bit, since I expect that I'll tweak the UI... :)

**Comment by iandoug** [comment]
Yeah, no problem, I was not wild about it myself. :-), I just tried to make is usable rather than beautiful, since making things beautiful is where I normally call in an artist :-)

I suppose we could add a "Make everything a decal" option too ... though for the PDF request we would also need a "Vanish existing decals" button first.

I've started looking at "make a PDF in Javascript" libraries .. firstly jspdf, which relies on html2canvas, and I don't think is the right approach since it seems to basically use the 'turn the screen into an image and put it in a PDF' approach. There's also pdfmake, which offers fine-grain control and the ability to embed fonts etc, so want to see what I can do with that. It reminds me of the PDF library for PHP, which name escapes me now, but I've worked with it in the past.

Something else which the voice in my head says I should do is add a table on the summary page, with all the legends on... ie a table with 12 columns x (keys) rows, just showing all the legends used on the keys. Alternatively a table with the key legends rerendered sans the keycaps. This would be a step towards producing the life-size PDF requested.

**Comment by ijprest** [comment]
OK, I've merged & published this.  Changes:
* Overhauled the UI:
  * Made it a tab, instead of a dialog, so that you could clearly see the effect of the tools
  * Styled the radio buttons, etc., to look like oversized keys.  :)
  * Replaced the "move pairs" buttons with an "align labels" function, that I think is more generic, and covers *most* of the use-cases for the old buttons (except the 'swap' button).
* Made the tools undo-able.  FYI: all you really have to do is wrap your changes in a call to transaction()
* Used a few Angular & JS tricks to reduce code size (mostly using ng-repeat to avoid having to list out all the various buttons).

**Comment by iandoug** [comment]
Cool. I was in two minds as to go the tab or dialogue route, I have some other tabs up my sleeve and was worried about the tabs getting a bit crowded. But I agree, it is better to be able to clearly see the effects of the tools. 
I also did consider creating oversize buttons but actually thought you would not like the idea and that it just be wasted effort. I think perhaps we need a tooltip over the From and To arrays, because the tooltip on the Go button refers to my previous labels of From and To, which are no longer there.
The other consolidated button is a nice idea. I admit I did find it a bit confusing at first, probably because I was familiar with my versions and the consolidated version threw me a bit. After playing with is a bit it became clearer :-)
I was hoping/expecting you would be able to make the things undo-able, thanks.
Thanks for the Angular lesson.. I am not yet able to Think in Angular, have not played with it enough. I realised that my code could be rewritten to be less verbose/consolidated but I think I kept some things separate in case another use case came along which didn't fit into the consolidated version so well, but into one of the other routines. Let me send you some stuff via email...

**Pull request merged**
