### PR TITLE
Add JD40 standard(ish) layout

### PR DESCRIPTION
**Pull request by jasonm23**
screen shot 2015-07-19 at 12 14 26 pm

### CODE REVIEW

**Comment by jasonm23** [comment]
It's a little difficult to get consensus on this layout, most designers seem to go their own way on the JD40 modifiers.

Happy to get any comments / corrections on this with "official" sources.

**Comment by jasonm23** [comment]
Here's one of the original 40%s by JD

**Comment by jasonm23** [comment]
I think I should switch it to this.   Making a different modifier/buckybit layout would be simple for anyone who wanted to via the UI.

**Comment by jasonm23** [comment]
Please hold until I push the update

**Comment by jasonm23** [comment]
On further thought, the submitted layout is probably suitable for people making JD40's from PCBs, (which I assume is the majority.) so I don't think it's really required to hand hold on modifier selection.

Anyone who needs to move things around will be more than capable in the kle.

**Comment by jasonm23** [comment]
Please merge unless you have reservations yourself.

**Comment by jasonm23** [comment]
Ok to merge?

**Comment by ijprest** [comment]
Merged... thanks.

**Comment by jasonm23** [comment]
Thanks

**Pull request merged**
