### PR TITLE
Add css link for custom fonts etc.

### PR DESCRIPTION
**Pull request by jasonm23**
Allow a CSS link to be added to layout for inclusion of custom styles / icons / etc.

### CODE REVIEW

**Comment by jasonm23** [comment]
perhaps I should add a regexp such as 

```
^(https?:)?\/\/[^ ]*?.css$
```

To force validation of the meta.css field.

Seemed unneccessary to me, but you be the judge.

**Comment by ijprest** [comment]
This is an interesting approach... essentially solves issue #19 (referencing external images/glyphs).

Any concerns about security/XSS-type attacks, I wonder?  I know older browsers could embed JS inside stylesheets... not sure if all the attack vectors have been closed.

It might be best to "sanitize" the CSS and only allow rules on font-awesome-style <i> tags, or something.  (A side benefit of parsing the CSS... when I eventually implement a character picker for #18, it could automatically include all the custom bits from the user-supplied stylesheet.)

Thoughts?

P.S., that's am impressively large layout... maybe we should think about "pinning" the edit-controls to the bottom of the browser and only scroll the keyboard layout?

**Comment by ijprest** [comment]
I found a ready-made CSS parser... I'm going to see what I can do quickly...

**Comment by ijprest** [comment]
OK... check out my "[custom-css](https://github.com/ijprest/keyboard-layout-editor/tree/custom-css)" branch and let me know what you think.

Instead of a *link* to a stylesheet, I embed the CSS right into the layout.  I'm also parsing the CSS and modifying all the rules so that they can only apply to keycaps within the keyboard area.

Pros: 
* layout is (a bit) more self-contained; if you only wanted to change your font (to, e.g., something on Google's font CDN), you might not need to host anything yourself.
* You can live-edit the CSS and not run into problems with your browser caching it.
* Custom CSS can't completely screw up the editor by styling non-keycap elements.
* Can easily filter out any problematic CSS... e.g., IE's "behaviours", which can be used to run arbitrary JS code.
* As mentioned above, since we're parsing the CSS, we could automatically include custom glyphs and stuff in a future character-picker.  Could potentially have a "create new glyph" feature where you could select a font/character and automatically add the necessary CSS.

Cons: 
* Layouts with CSS are bigger... I'll probably need to relax my 8kb limit on saved layouts.
* The CSS Parser I'm using seems to have a few minor bugs (mostly whitespace related).  Luckily it's a Jison-based parser, so it should be straightforward to fix.

Thoughts?

**Comment by jasonm23** [comment]
Nice.  I think it would be better, for an example, to put the petscii class into the custom css too.  

So people can see what's possible, more easily.

**Comment by jasonm23** [comment]
I think you should merge in your Custom-css branch, it's a nicer solution than this one for sure.

**Comment by ijprest** [comment]
Will do... I'm just preparing to deploy another (largish) change, and trying to touch up the scripts and stuff to handle the post-Bower layout.  

I'll merge & deploy this tomorrow night.

**Comment by jasonm23** [comment]
:)

**Comment by ijprest** [comment]
Took me a while to fix the CSS parsing errors... eventually I just wrote my own parser.  It's done now, and deployed to the live server.

Thanks again for the idea & initial implementation!

**Pull request merged**
