### PR TITLE
Small corrections to json files

### PR DESCRIPTION
**Pull request by iandoug**
as per email

### CODE REVIEW

**Comment by iandoug** [comment]
Save as PNG uses free code borrowed from 
http://html2canvas.hertzen.com/
Comment 16 here: http://stackoverflow.com/questions/6887183/how-to-take-screen-shot-of-a-div-with-javascript
https://github.com/eligrey/canvas-toBlob.js (Same guy as FileSaver.js already used)
Issues :
1. "Save" buttons now have square corners on one side. You probably know the trick to fix that.
2. The save includes the whole background (screen width). I tried various things to pass the background as a parameter to the function without success.
3. Some fonts and FontAwesome glyphs do not render properly. In particular the Commodore keyboard fails because it can't find the engravers font ... this may work on live site where you have the font. Otherwise in general it does a reasonable job for an 'experimental' release :-)

**Comment by iandoug** [comment]
#74 addressed in 292624b

**Comment by iandoug** [comment]
html2canvas.js should probably be managed via bouwer. I took a quick look and it wasn't immediately obvious where I should add it, so didn't ... :-). Moved it from js/ to root to let git pick it up.

**Comment by ijprest** [comment]
OK, will start pulling now.

**Comment by ijprest** [comment]
OK, I'm still working on this.  I was trying to get the switch-type combo boxes to behave nicely (disable when appropriate, etc.), and Angular was giving me lots of grief with the &lt;select&gt; objects related to the order in which it evaluates bindings... so this is taking a bit longer than expected.

I'm close, though... I should be able to finish this up tomorrow night.

**Comment by iandoug** [comment]
On Sunday 09 August 2015 21:10:09 Ian Prest wrote:

>  I was trying to get the switch-type combo boxes to behave nicely (disable
> when appropriate, etc.),

Yeah I realised last night it wasn't always working as I had imagined it 
should be ... sorry didn't do enough testing.

> and Angular was giving me lots of grief 

:) Tell me about it :-)

On another issue, "Paste" tends to put keys in weird places. Especially when 
the key is rotatated. For example, if I copy a rotated key, then paste, it is 
often off-screen at bottom left. Only way to find it is ctrl-A to select 
everything, then move everything right until it scrolls into view.

So possibly it may be best to always add at 0,0? Or some specific dedicated 
position?

I copy and paste instead of Add New to keep colours and rotation etc.

cheers, Ian


-- 
ian@zti.co.za http://www.zti.co.za
Zero 2 Infinity - The net.works
Phone +27-21-975-7273

**Comment by ijprest** [comment]
OK, merged & deployed.  I had to switch to a bootstrap-style dropdown, but think I finally got the combos to behave nicely (in all the scenarios I tried).

My changes, mostly minor (other than the combo stuff):
* Getting html2canvas via bower
  * It's pretty easy, FYI: `bower install html2canvas --save --save-exact`
  * Even if it's not in the [bower package repo](http://bower.io/search/) (this one was), you can always use bower to install from a GitHub repo.  It's pretty slick.
* Added a (tiny) polyfill for HTMLCanvasElement.toBlob() that I cribbed from mozilla.org; tested and working on IE & Chrome.
* Made the 'Download SVG' button into an Angular-style button.
* Put all the 'Download' options under a dropdown to unclutter the UI a bit.
* Changed serialization of sm/sb/st to round-trip better
  * You were setting all keys to the default on load, which would unnecessarily get written back out during the save.
  * Now just leaving it as an empty string internally, and the UI knows to show the default if there isn't a per-key override.
* Disabling the combos and stuff when appropriate (e.g., when no key selected, etc.)
* Had to switch to bootstrap-style dropdowns, as mentioned above.  Mostly because Angular evaluated an `<option>` value bindings earlier than its dependencies were evaluated, and so it got confused and ended up adding a bunch of "empty" options in the dropdown, which was ugly.

P.S., I can see how copy/paste on rotated keys can sometimes be confusing... but even (0,0) isn't enough to solve it in all cases.  I'll add a bug to track this.

**Comment by iandoug** [comment]
hi Ian

On Monday 10 August 2015 18:59:18 Ian Prest wrote:

> OK, merged & deployed.  I had to switch to a bootstrap-style dropdown, but
> think I finally got the combos to behave nicely (in all the scenarios I
> tried).

Cool. Not wild about how those dropups look but I can imagine it was the 
result of hours of frustration... :-)

I see the list is now sorted differently to before .. am guessing it's sorted 
on part name, is it possible to sort for example on the displayed string 
instead?
 

> My changes, mostly minor (other than the combo stuff):
> * Getting html2canvas via bower
>   * It's pretty easy, FYI: `bower install html2canvas --save --save-exact`
>   * Even if it's not in the [bower package repo](http://bower.io/search/)
> (this one was), you can always use bower to install from a GitHub repo. 

thanks.

> It's pretty slick. * Added a (tiny) polyfill for HTMLCanvasElement.toBlob()
> that I cribbed from mozilla.org; tested and working on IE & Chrome.

Yeah, I saw something about that somewhere, but at the moment I'm with Google 
regarding browser support ... Current version and previous versions only, 
trying to support legacy is a recipe for madness. Which is why I don't think 
all those browser-specific css keywords are necessary anymore ... 

> * Made
> the 'Download SVG' button into an Angular-style button.
> * Put all the 'Download' options under a dropdown to unclutter the UI a bit.

Great, was hoping you would do that, I've added the Save as JPG as well... 
it's basically an extension of the save as png, So in theory we should use the same 
code and just pass the format as a parameter, but on the other hand it may make sense 
to keep them separate in case a better solution for one of them comes along ...

Issue: background is black. Maybe not an issue.
Issue 2: works fine for slabs, not so fine for rotated, but I see the same issue with 
savePng. So did you change something? SavePNG was working fine before.
See attached.
Have not pushed saveJPG yet. Actually spent some hours barking up the wrong tree 
trying to do things with a div which it not a canvas until you make it one :-)


> * Changed serialization of sm/sb/st to round-trip better
>   * You were setting all keys to the default on load, which would
> unnecessarily get written back out during the save. * Now just leaving it
> as an empty string internally, and the UI knows to show the default if
> there isn't a per-key override.

Yeah, thought you might do that :-). I actually did it on purpose because one 
of the things that bothers me about the UI is that if the values are DEFAULT 
then nothing gets displayed, and I prefer to see everything clearly. However I 
understand your reasoning for the way it works too, to minimise the size of 
the json output.

Cheers, Ian

-- 
ian@zti.co.za http://www.zti.co.za
Zero 2 Infinity - The net.works
Phone +27-21-975-7273

**Comment by iandoug** [comment]
"3. Some fonts and FontAwesome glyphs do not render properly. " .... seeing this with some FontAwesome icons, particularly the handbag lock.

My previous observation revealed it's cause when I started converting PKB into another design .. I did something that changed the spacing, and the handbag lock suddenly revealed itself as an up-arrow in a solid circle, superimposed on the lock. However that was not in the code for the key legend. IIRC I manually typed them in and certainly never put the uparrow there. I retyped it and it was fixed. Now however I notice the locks are broken. See PKB on live site, download as png, then look at lock under green LED or on the two shift keys.
So either there is a bug in FontAwesome or I dunno ... :-) ... can't think that there would be anything in your code to mess up one character.

**Comment by iandoug** [comment]
On Tuesday 11 August 2015 17:36:50 Ian Douglas wrote:

> Cool. Not wild about how those dropups look but I can imagine it was the 
> result of hours of frustration...

okay cancel that.

First time I loaded it, the downarrows were below the text in a separate line, 
hence 'not wild about how they look' but today they are where they are supposed 
to be .. maybe I needed to hard-reload or somesuch and didn't.

cheers, Ian
-- 
ian@zti.co.za http://www.zti.co.za
Zero 2 Infinity - The net.works
Phone +27-21-975-7273

**Pull request merged**
