### PR TITLE
Added Download as JPG

### PR DESCRIPTION
**Pull request by iandoug**
Decided to push it anyway since the issue is not with the save but somewhere else.

### CODE REVIEW

**Comment by iandoug** [comment]
Adding the thumbnail thing took WAY longer than I thought it would .... only my stubborness to get it working paid off in the end. Tried multiple ways to get the canvas to resize, including creating a clone of the canvas or clone of the div and went round in circles ... managed to get right size canvas, but nothing on it. Eventually found what I needed in the answer here:
http://stackoverflow.com/questions/20555386/canvas-image-to-blob-changing-image-size

I arbitrarily set the target width at 110px based on the samples referenced in #15

**Comment by iandoug** [comment]
Re the summary, it does not look as pretty as I would like. I can't persuade that extra horizontal rectangle above the text to go away. Tried putting the switch data in a table but that didn't work because of the div repeat breaking the table HTML correctnesss. There probably is a way to do it.
Consider it a first step to something better... :-)

**Comment by iandoug** [comment]
Re the switch counts, would be more correct if the brand names were Capitalized in the switches.json ... did not want to change that in case you wanted it that way for a reason. Will probably also break existing saved json files to some extent, but that's easy to fix. Address issue #88.

**Comment by iandoug** [comment]
Ideally I should check if the key colour matches a known key colour (eg SP PBT xxx) and print that as well ... there is a chance that a colour may occur twice in different ranges from different suppliers...

**Comment by ijprest** [comment]
Thanks... merged & published.  Made a couple of very minor tweaks to the formatting of the summary tab (will probably do more later, but no sense delaying this until then).

**Pull request merged**
