### PR TITLE
Webfont

### PR DESCRIPTION
**Pull request by iandoug**
Hi
Okay as per the fun and games in my email, reconstituted the svg files via fontforge export from the .svg version of the font. So all the pretty names you and I had created got lost, I can rebuild them later. 

Other changes: 
1. moved the svg files from font-src to font-src/kbd-custom. I intend to create a font-src/combining-diacritics, then recreate the glyphs by extracting from Symbola font, then make it work like FontAwesome and kbd-webfont, since that works so nicely.

2. Tweaked the css for the glyphs a bit, to make them larger and easier to see. Hope it didn't break any of the other fontpicker collections, they all look okay on my system. You said some of them were there to try to force the combining stuff nice, hopefully they won't be needed soon.

3. Still having issues with the Makefile ... I tried drastic surgery but got nowhere so left as is except for a comment for myself. The code you have there referencing the .svg glyphs is now incorrect, since I wiped them with git rm (inadvertently), I tried checking them out again but that failed so it may be wise to zip everything up before starting. Also that list was missing the other ones I added... it was going to get long anyway so I thought it would be easier/simpler to do everything in the .pe file, instead of trying to generate the .pe file and then generate the fonts afterwards. So the .pe file now generates the usual suspects for the web.

I stuck this in a separate branch because of all the above ... not sure what you will approve of or not :-)

Anyway it should go some ways to resolving issue #17 

Cheers, Ian

### CODE REVIEW

**Comment by ijprest** [comment]
OK... I finally got around to this one.  (It wasn't as bad as it looked, since a lot of the changes GitHub referenced above were actually from another pull-request.)

I made the makefiles work (on my system), and fixed a few minor things (references to files that didn't exist, one spelling mistake, etc.), but didn't really change anything.

I noticed that the combining-diacriticals.css was mentioned, but doesn't exist... did you forget to add this or something?

Anyway... thanks again.

**Comment by iandoug** [comment]
On Sunday 30 August 2015 16:58:49 Ian Prest wrote:

> I noticed that the combining-diacriticals.css was mentioned, but doesn't
> exist... did you forget to add this or something?

yes, looks like at some point when I as 'cleaning up' I moved it to an Unused 
folder.

Have pushed it to the webfont branch on github.

You'll also need to change here in the Makefile:
# Rules to run Stylus on our .css files
css_files: css/kb.css css/kbd-webfont.css css/combining-diacritical.css

Cheers, Ian

-- 
ian@zti.co.za http://www.zti.co.za
Zero 2 Infinity - The net.works
Phone +27-21-975-7273

**Comment by iandoug** [comment]
On Sunday 30 August 2015 16:58:49 Ian Prest wrote:

> OK... I finally got around to this one.  (It wasn't as bad as it looked,
> since a lot of the changes GitHub referenced above were actually from
> another pull-request.)

kbd-webfont not working for me on live system ... looks like generated font is 
not there, but the css is.

In fact it appears that it's trying to show a combining-diacritical glyph 
instead of the webfont glyph.

I haven't synced with your master yet.

cheers, Ian
-- 
ian@zti.co.za http://www.zti.co.za
Zero 2 Infinity - The net.works
Phone +27-21-975-7273

**Comment by iandoug** [comment]
On Sunday 30 August 2015 16:58:49 Ian Prest wrote:

> I made the makefiles work (on my system), and fixed a few minor things
> (references to files that didn't exist, one spelling mistake, etc.), but
> didn't really change anything.

make install and make both run through without errors now.

I see the old names for the diacritical svgs (before I fixed them) are still 
there... I thought git handled removing them. Maybe I need to specifically 
remove them?

thanks, Ian
-- 
ian@zti.co.za http://www.zti.co.za
Zero 2 Infinity - The net.works
Phone +27-21-975-7273

**Pull request merged**
