### PR TITLE
Create symbolics-spacecadet

### PR DESCRIPTION
**Pull request by jasonm23**

### CODE REVIEW

**Comment by jasonm23** [comment]
Hold on! ... fixing :)

**Comment by jasonm23** [comment]
Having some issues loading the preset, any tips/pointers?

**Comment by jasonm23** [comment]
Notes... 

I'm getting "requested layout does not exist" error. (after setting base_href to `http://localhost:1234`)

I see the layout loaded via xhr / `loadSample`, but not hitting `.success` just falling through to `.error`.

If I load the file via the rawdata uploaded, it's fine.

**Comment by D1SC0tech** [comment]
Make sure that your JSON is properly escaped, e.g. backcolor should be changed to "backcolor".

**Comment by jasonm23** [comment]
Got it.

**Comment by jasonm23** [comment]
Fixed

**Comment by ijprest** [comment]
Cool keyboard.  Merged.  Thanks for the contribution.

**Comment by jasonm23** [comment]
Just noticed a small error - "MODE LOCK" should be "ALT LOCK" (bottom right)

**Pull request merged**
