### PR TITLE
Fixed a few issues in Programmers Keyboard, added LEDs and logo.

### PR DESCRIPTION
**Pull request by iandoug**
As per subject. Dunno if it's easier to use the email attachment or to do it via github.
Cheers, Ian

### CODE REVIEW

**Comment by ijprest** [comment]
Thanks.  I took the liberty of also fixing the one that you couldn't fix because of that bug you found.

P.S., since links to saved "GitHub Gist" layouts are now stable (i.e., the link doesn't change every time you tweak your layout), if you save your layout we could just link to your saved one, which would then always be up to date.  Your call... whatever works better for you.

**Comment by iandoug** [comment]
On Wednesday 05 August 2015 20:01:06 Ian Prest wrote:

> P.S., since links to saved "GitHub Gist" layouts are now stable (i.e., the
> link doesn't change every time you tweak your layout), if you save your
> layout we could just link to your saved one, which would then always be up
> to date.  Your call... whatever works better for you.

Um, when working locally, the login to github part does not seem to work ... I 
got a screen asking me to give you read/write permission, but then it appeared 
to hang.

I've just tried now on your live site, which does appear to work, but your 
site then proceeded to set 45 (yes, 45) cookies ... is that normal?

I've got a Firefox configured to 'ask' me about every cookie request ...  So I 
selected "for Session" for all of them ...

And then Firefox closed itself...  

Bit buggy? :-)

cheers, Ian
-- 
ian@zti.co.za http://www.zti.co.za
Zero 2 Infinity - The net.works
Phone +27-21-975-7273

**Comment by iandoug** [comment]
On Wednesday 05 August 2015 20:01:06 Ian Prest wrote:

> P.S., since links to saved "GitHub Gist" layouts are now stable (i.e., the
> link doesn't change every time you tweak your layout), if you save your
> layout we could just link to your saved one, which would then always be up
> to date.  Your call... whatever works better for you.

Firefox would not start, had to restart GUI. Bug in firefox.

Anyway, KLE shows me my github profile picture and options, but "Save" is 
still disabled.

Could this be because I allowed the cookies for Session only (but then, why 
does Github think I am logged in?)

cheers, Ian
-- 
ian@zti.co.za http://www.zti.co.za
Zero 2 Infinity - The net.works
Phone +27-21-975-7273

**Comment by ijprest** [comment]
Not sure why you saw 45 cookies... KLE is only storing one cookie (confirmed in both Chrome & FF developer tools), but it's possible the GitHub login page was doing stuff.

The OAuth login process is pretty annoying.  Show popup.  Popup goes to GitHub, where you log in.  GitHub redirects the popup back to KLE, with a parameter.  KLE has to then make a call to a web service (that I'm hosting on Azure) to convert that parameter into an OAuth token.

So, due to the GitHub redirect, if you want to log in locally, you'll have to be hosting on http://localhost:8080 (I call this out in the README).  So that *might* be your problem with local-hosted login.  (It's possible to work around, but you'd have to hack the code with your own GitHub appliation ID, and host your own instance of [Gatekeeper](https://github.com/prose/gatekeeper).  I'm running two instances of Gatekeeper and have two GitHub application IDs; one each for the live site & for localhost:8080.)  

Finally, if you're logged in, I think the only reason the 'save' button would be disabled would be if the layout isn't 'dirty'.  Making any change to the layout should dirty it.

**Comment by iandoug** [comment]
On Thursday 06 August 2015 10:07:48 Ian Prest wrote:

> Not sure why you saw 45 cookies... KLE is only storing one cookie (confirmed
> in both Chrome & FF developer tools), but it's possible the GitHub login
> page was doing stuff.

I also immediately suspected Github (as I could not image why you would need 
45 cookies) but Firefox listed the site setting them as KLE.
Firefox only shows 1 cookie (oauth) stored from your site.

Only thing I can think of is that you have some loop or something 
setting/checking and it ran faster than what I could accept the first cookie 
then it got into a loop. But that's a rather weird explanation.

> So, due to the GitHub redirect, if you want to log in locally, you'll have
> to be hosting on http://localhost:8080 (I call this out in the README).

Apologies, saw that a few days ago and promptly forgot about it :-)

> Finally, if you're logged in, I think the only reason the 'save' button
> would be disabled would be if the layout isn't 'dirty'.  Making any change
> to the layout should dirty it.

Yes, that worked. While we're on the topic, is there a reason why the font 
size is not shown on keys already done, if it is default 3? Then when you hit 
the adjust buttons it starts at 1. 

It's Thursday night so I've got to do movies as well as some Work Work so 
won't be able to fiddle on KLE... :-)

cheers, Ian

-- 
ian@zti.co.za http://www.zti.co.za
Zero 2 Infinity - The net.works
Phone +27-21-975-7273

**Pull request merged**
